version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: static-nginx
    ports:
      - "8502:8502"
    volumes:
      # - ./:/usr/share/nginx/html/static # แชร์โฟลเดอร์ static ให้ NGINX
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # ใช้คอนฟิก nginx.conf